from __future__ import annotations

MODE_MANIFEST = {
    "key": "default",
    "name": "默认模式",
    "summary": "处理除测试以外的通用协作、问答、调度与工作台能力。",
    "description": "默认模式承接当前系统已支持的综合能力，优先走 Coordinator 与现有通用工具链。",
    "category": "general",
    "is_test_mode": False,
    "case_driven_policy": "exempt",
    "default_agent_key": "coordinator",
    "allowed_agent_keys": ["coordinator", "ops-executor", "report-analyst", "qa-planner"],
    "default_skill_keys": [],
    "registered_tool_keys": [
        "workflow-router",
        "subagent-dispatch",
        "knowledge-rag",
        "web_search",
        "attachment-reader",
        "session-history",
        "session-timeline",
        "observation-search",
        "cli-executor",
        "report-writer",
    ],
    "harness_key": "default_conversation_harness",
    "activation_policy": "auto",
    "core_capability_keys": ["general.assistance", "web.search"],
    "on_demand_capability_keys": ["api.documentation.read", "report.generate"],
    "placeholder": False,
    "tags": ["default", "general", "coordinator"],
}
