from __future__ import annotations

MODE_MANIFEST = {
    "key": "api_testing",
    "name": "API接口测试模式",
    "summary": "面向接口校验、契约检查、响应断言与证据沉淀。",
    "description": "API 接口测试模式提供专属 Agent 和接口测试工具链，统一处理接口验证任务。",
    "category": "testing",
    "is_test_mode": True,
    "default_agent_key": "api-testing-agent",
    "allowed_agent_keys": [
        "api-testing-agent",
        "api-executor-worker",
        "api-project-clarifier",
        "api-doc-analyst",
        "api-suite-planner",
        "api-precondition-planner",
        "api-failure-analyst",
        "report-analyst",
    ],
    "default_skill_keys": [
        "api-contract-testing",
        "api-test-generation",
        "test-data-strategy",
    ],
    "registered_tool_keys": [
        "api-test-runner",
        "api-docs-library",
        "api-tester",
        "knowledge-rag",
        "report-writer",
    ],
    "harness_key": "api_testing_harness",
    "activation_policy": "auto",
    "maximum_auto_risk_level": "medium",
    "core_capability_keys": ["api.validation", "api.documentation.read"],
    "on_demand_capability_keys": ["performance.load_test", "security.assessment", "report.generate"],
    "public_entry_tool_key": "api-test-runner",
    "allowed_subworkflow_keys": ["performance_testing", "security_testing"],
    "placeholder": False,
    "tags": ["testing", "api", "contract"],
}
