[project]
name = "enterprise-ai-qa-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["enterprise-ai-qa-agent-server"]

[dependency-groups]
dev = ["enterprise-ai-qa-agent-server[dev]"]

[tool.uv.sources]
enterprise-ai-qa-agent-server = { workspace = true }

[tool.uv.workspace]
members = ["Agent_Server"]
